### ISSUE TITLE
Adding additional tracks

### ISSUE THREAD

**Issue by bistace** [sanger-tol/PretextView#21]
Hi and thank you for developing the Pretext suite!

I have successfully generated and edited a contact map and was wondering if there was any way to add some additional informations. I would like to add the position of some elements (repeats as an example) thanks to a file containing their positions. Would this be possible to do in PretextView/PretextSnapshot?

**Comment by additive3** [comment]
These information can be embeded in a Pretext image file using [PretextGraph](https://github.com/sanger-tol/PretextGraph)
