### ISSUE TITLE
No Extensions Available in PretextView Menu

### ISSUE THREAD

**Issue by foreignsand** [sanger-tol/PretextView#24]
I have PretextView version 0.2.5 for Mac OSX and I can't find the Extensions Menu demonstrated at 47:08 in [this video](https://www.youtube.com/watch?v=F5jvh3owzl4). Is this available for my version of PretextView and if it is, should it be native or do I need to somehow add the functionality to the software?

Many thanks!

**Comment by additive3** [comment]
Ho @foreignsand 
The Extensions menu will appear if these supplementary information (eg coverage) are embedded in the Pretext image file.
[PretextGraph](https://github.com/sanger-tol/PretextGraph) is used to embed BedGraph format files
