### ISSUE TITLE
Metadata tags

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/PretextView#27]
Hi, I am so sorry for opening up another issue, I am currently assembling an autotetraploid genome on Pretextview and I am trying to tag this with hap1, hap2, hap3 and hap4. I believe that "m" brings up the metadata tagging options and I use the arrow keys to swipe through the meta tags which I edited in the menu. I also thought that once I selected the metatag, I can place it onto a scaffold by left click, but this does not seem to be working. I have also tried different keys and mouse clicks but can't seem to place the meta tag? I also have the latest version, so I'm not sure why I can't tag the different haplotypes? My interface looks like this: 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/53db671d-8677-4ece-999c-472ea125cfad">

Any advice would be great! Thank you!!

**Comment by additive3** [comment]
Hi @Rhia15 
Can you quit and re-open the the application on which ever monitor you are using to edit the contact map please.
I think that should resove the visual issue you are seeing.
This looks reminicent of an issue with display swapping, it is something that is being looked into - the information are present just not visible.

As an aside, I note there is quite a bit of scaffold errors remaining in your painted scaffolds, this in part is why your haplotype clusters are quite disparate

**Comment by Rhia15** [comment]
Hi, Thank you for the reply, yes this worked great!!

In terms of the haplotype clusters being disparate, does this mean in terms of size? Please can I ask how you picked out the scaffolding errors? I'm finding it quite hard to recognise them, and i'd love to learn! Is it simply based on a specific pattern? :) 

Also, when adding these metadata tags, I noticed that if one scaffold is made up of smaller scaffolds, each of scaffolds making up the larger scaffolds have to be tagged, is that correct? Or should I be tagging these in a different way? I.e tagging scaffold 20 as Hap4 in the image. I was just wondering as I wasn't sure if this would mess up the downstream processing. 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/ca106781-12c0-4bd0-88a3-2f9ee2882558">
 
Thank you very much!

**Comment by additive3** [comment]
Hi @Rhia15 

Tagging haplotypes/sex chromosomes only needs to be done once in the painted scaffold area.
The only Individual scaffolds that need tagging in a painted area UNLOC designated sequences. These need to also be placed at the start or end of the region.


Yes, I notoce that there are duplications of sequence in some of the scaffolds that should be moved to the other scaffolds. There are other arragement errors visible too. In your above image there is a region at the start of Scaffold_19 that is duplicated in the middle. Looking across at Scaffolds 17 and 20 we can see that thst sequence appears 4 times (consistent with the tetraploid genome) thus that first copy (which also has no Hi-C linking at its current position should be moved to the 4th copy of that chromosome.
If you would like to learn more about curatign genomes BGA24 is running a [Curation Workshop](https://thebgacademy.org/BGA24/sessions/Genome-Curation) in the near future.

**Comment by Rhia15** [comment]
Hi, Thank you so much for all the advice! :) Super useful!
