### ISSUE TITLE
Dual curation pipeline 

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/PretextView#28]
Hi, this might be a bit of a dumb question, but I just realised there was a dual curation pipeline (I was previously assembling hap1 and hap2 separately with a YaHs pipeline). I have read the manual_genome_curation.pdf and came across this workflow: 
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/4f34d2d3-9f27-4714-9e1c-09f641fc542b">

I was wondering if you would scaffold the initial assemblies before (Hap1, Hap2 separately) or after concatenating the two Haplotypes? Or would this really not matter? 

Do you also have a preferred scaffolding tool? I was using YaHs for diploids (HapHic seemed to have a very sparse interaction map) and HapHic for the higher ploidies because I wasn't sure how to get all haplotypes from the dual curation pipelines. Would HapHic also be something you would use with Pretext? 

Apologies for opening this up as an "issue", I understand it's not an issue but I wasn't sure where I could ask these questions, is there a google group perhaps? :) I also found the two youtube videos on manual curation extremely useful, I was wondering if there is a similar video for higher ploidies e.g tetraploids? 

Thank you very much!! :)

**Comment by additive3** [comment]
Hi @Rhia15 

For a diploid the normal workflow would be to produce a scaffolded assembly for each haplotype before concatenating and curating.
However it is not necessarily so straighforwards, especially for polyploids.
I've not used HapHic so I cannot comment, but a fasta produced from that tool could be made into a PretextView contact map.

>  is there a google group perhaps?

No, but there is a [Slack channel](https://join.slack.com/t/assemblycuration/shared_invite/zt-1kx2ww71y-823ruaAxswgQGypgofBaOA) you can join!

> if there is a similar video for higher ploidies e.g tetraploids?

No, but watch this space...

**Comment by Rhia15** [comment]
Ah thank you so much! Will look out for that video ahaha ;)
